/**
 * AI Studio Bridge - Auto-Generated Exports
 * 
 * This file is automatically generated after each sync from AI Studio.
 * It exports all TypeScript/JavaScript modules synced via git subtree.
 * 
 * Usage in app code:
 *   import { Something } from "@/ai";
 *   import { specific } from "@ai/specific-module";
 * 
 * GENERATED: 2025-12-30T13:29:49.916Z
 */

// Version constant for tracking
export const AI_STUDIO_VERSION = "1.0.0";
export const AI_STUDIO_SYNCED_AT = "2025-12-30T13:29:49.916Z";

// ============================================
// AUTO-GENERATED EXPORTS FROM AI STUDIO SYNC
// ============================================

// Synced: App.tsx
export * from "./App";

// Synced: components/ColorTempSlider.tsx
export * from "./components/ColorTempSlider";

// Synced: components/Dimmer.tsx
export * from "./components/Dimmer";

// Synced: components/LightBulb.tsx
export * from "./components/LightBulb";

// Synced: components/Toggle.tsx
export * from "./components/Toggle";

// Synced: index.tsx
export * from "./index";

// Synced: services/audioService.ts
export * from "./services/audioService";

// Synced: services/geminiService.ts
export * from "./services/geminiService";

// Synced: types.ts
export * from "./types";

// Synced: vite.config.ts
export * from "./vite.config";
